// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdtnLFbYKq-jtQLVmSqPamn2dMLBDZKTo',
    appId: '1:819349300499:web:6dc772f4a4fe5aa64ca6e6',
    messagingSenderId: '819349300499',
    projectId: 'taskapp-d8595',
    authDomain: 'taskapp-d8595.firebaseapp.com',
    storageBucket: 'taskapp-d8595.appspot.com',
    measurementId: 'G-FENEV5EZSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9cuM9O4Y0XjxFGMbHoQ2p4rb7TjtFFkw',
    appId: '1:819349300499:android:4b7d160c6343f91a4ca6e6',
    messagingSenderId: '819349300499',
    projectId: 'taskapp-d8595',
    storageBucket: 'taskapp-d8595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh7p4bJ3WuRENZtesw0uoEvcH3s3Hq6rM',
    appId: '1:819349300499:ios:f45818867e2390404ca6e6',
    messagingSenderId: '819349300499',
    projectId: 'taskapp-d8595',
    storageBucket: 'taskapp-d8595.appspot.com',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh7p4bJ3WuRENZtesw0uoEvcH3s3Hq6rM',
    appId: '1:819349300499:ios:f45818867e2390404ca6e6',
    messagingSenderId: '819349300499',
    projectId: 'taskapp-d8595',
    storageBucket: 'taskapp-d8595.appspot.com',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdtnLFbYKq-jtQLVmSqPamn2dMLBDZKTo',
    appId: '1:819349300499:web:9889e4efae493ba84ca6e6',
    messagingSenderId: '819349300499',
    projectId: 'taskapp-d8595',
    authDomain: 'taskapp-d8595.firebaseapp.com',
    storageBucket: 'taskapp-d8595.appspot.com',
    measurementId: 'G-3P3VZSDWS0',
  );
}
